accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('accounts/', include('accounts.urls'))
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page to view all blogs that have been created.
    path('blogs/', views.blogs, name='blogs'),
    # Page to view an individual blog, and all its posts.
    path('blog/<int:blog_id>/', views.blog, name='blog'),

    # Page for creating a new blog.
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for writing a new post.
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # Page for editing an existing post.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    """Represents one person or organization's blog."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the blog."""
        return self.name


class BlogPost(models.Model):
    """Represents an individual post."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    title = models.CharField(max_length=500)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representing the blog post."""
        return f"{self.title[:50]}..."

blogs/forms.py
from django import forms

from .models import Blog, BlogPost


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']
        labels = {'name': ''}


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body']

        widgets = {'body': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm


def index(request):
    """The home page for Blog."""
    return render(request, 'blogs/index.html')


@login_required
def blogs(request):
    """Page to view all blogs that have been newd."""
    blogs = Blog.objects.filter(owner=request.user).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)


@login_required
def blog(request, blog_id):
    """Page to view an individual blog, and all its posts."""
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blogpost_set.all()

    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)


@login_required
def new_blog(request):
    """Page to new a new blog."""
    if request.method != 'POST':
        # No data submitted; new a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:blogs')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


@login_required
def new_post(request, blog_id):
    """Page to create a new post."""
    blog = Blog.objects.get(id=blog_id)
    check_blog_owner(blog, request.user)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)

    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """Page to edit an existing post."""
    post = BlogPost.objects.get(id=post_id)
    blog = post.blog
    check_blog_owner(blog, request.user)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = BlogPostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)

    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)


def check_blog_owner(blog, user):
    """Make sure the currently logged-in user owns the blog that's
    being requested.

    Raise Http404 error if the user does not own the blog.
    """
    if blog.owner != user:
        raise Http404

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Blogs</title>
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
	<a class="navbar-brand" href="{% url 'blogs:index' %}">
      Blogs&Posts</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarCollapse" aria-controls="navbarCollapse"
			aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span></button>
	<div class="collapse navbar-collapse" id="navbarCollapse">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'blogs:blogs' %}">
					Blogs</a></li>
		</ul>
		<ul class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
				<li class="nav-item">
					<span class="navbar-text"> Hello, {{ user.username }}.</span>
				</li>
				<li class="nav-item">
					<form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-light">log out</button>
                    </form>
				</li>
			{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'accounts:login' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
<main role="main" class="container">
	<div class="pb-2 mb-2 border-bottom">
		{% block page_header %}{% endblock page_header %}
	</div>
	<div>
		{% block content %}{% endblock content %}
	</div>
</main>
</body>
</html>

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p>Blog: {{ blog.name }}</p>

  <p>Posts:</p>
  <ul>
    {% for post in posts %}
      <li>
        <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ post.title }}</p>
        <p>{{ post.body|linebreaks }}</p>
        <p><a href="{% url 'blogs:edit_post' post.id %}">Edit post</a></p>
      </li>
    {% empty %}
      <li>This blog does not have any posts yet.</li>
    {% endfor %}
  </ul>

<p><a href="{% url 'blogs:new_post' blog.id %}">Create a new post</a></p>
  
{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p>All Blogs</p>
  <ul>
    {% for blog in blogs %}
      <li>
        <a href="{% url 'blogs:blog' blog.id %}">
          {{ blog.name }}</a>
      </li>
    {% empty %}
      <li>No blogs have been created yet.</li>
    {% endfor %}
  </ul>

<p><a href="{% url 'blogs:new_blog' %}">Start a new blog</a></p>

{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.name }}</a></p>

  <p>Edit post:</p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% block content %}
    <p>Blogs</p>
    <p>You can create your own blogs here!</p>
{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}

{% block content %}
  <p>Create a new blog:</p>

  <form action="{% url 'blogs:new_blog' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Create blog</button>
  </form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a></p>

  <p>Create a new post:</p>
  <p><form action="{% url 'blogs:new_post' blog.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Create post</button>
  </form></p>

{% endblock content %}